services:
  - type: web
    name: cal-com
    runtime: node
    region: frankfurt
    plan: free
    autoDeploy: false
    buildCommand: bash render-setup.sh
    startCommand: yarn dev
    envVars:
      - key: RENDER_POSTGRES_CONN_STR
        fromDatabase:
          name: dev-postgres
          property: connectionString
          
      - key: RENDER_NEXTAUTH_SECRET
        generateValue: true
          
      - key: RENDER_CALENDSO_ENCRYPTION_KEY
        generateValue: true
        
      - key: RENDER_DAILY_API_KEY
        sync: false
  

databases:
  - name: dev-postgres
    region: frankfurt
    databaseName: caldb
    user: caluser
    plan: free
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 15


# available database envVars properties are listed below
    # host
    # port
    # database is the PostgreSQL database name (not the friendly name)
    # user
    # password
    # connectionString

# available regions
# oregon
# frankfurt
# ohio
# singapore
